import Head from 'next/head'
import { useEffect, useContext } from 'react'
import { useRouter } from 'next/router'

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import Search from '../../components/Search'
import Form from '../../components/Form'
import Display from '../../components/Display'
import { AppContext } from '../../components/Context';
// import Toggle from '../../components/mini-components/Toggle'
// import { darkMode } from '../../methods/Darkmode';


export default function Home() {
  const { setTokenId,getData,menu,setMenu,setTaskGroup } = useContext(AppContext)

  const router = useRouter()

  /* Checking if the user is logged in or not. If not, it will redirect to the Login page. */
  useEffect(() => {
    let token = sessionStorage.getItem("Token")
    setTokenId(token)
    if (token) {
      getData(setTaskGroup)
    }
    if (!token) {
      router.push("/")
    }
  }, [])


  return (
    <div className={`min-h-screen`}>
      <Head>
        <title>Next Firebase Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer position="top-right"
        autoClose={3000}
        newestOnTop={true}
        closeOnClick
        theme="colored"
      />
     
      <main >
        {/* <Toggle toggle={toggle} setToggle={setToggle} onClick={() => darkMode(setToggle)} /> */}
        <div className='fixed z-100 bottom-0 w-full max-w-full'>
          <div className='ml-4 mb-2.5'>
            <button className="menu" onClick={() => setMenu(!menu)}>Add or Search</button>
          </div>
          <div className="flex justify-center">
            <section className={`formContainer`} style={{ display: menu ? "block" : "none" }}>
              <div className={`flex justify-center`}>
                <Form />
              </div>
              <Search />
            </section>
          </div>
        </div>
        {/* READ TASKS */}
        <Display />
      </main>
    </div >
  )
}


